# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elhadji/Bureau/ProjetOCR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elhadji/Bureau/ProjetOCR/src

# Include any dependencies generated for this target.
include CMakeFiles/OCR.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/OCR.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/OCR.dir/flags.make

CMakeFiles/OCR.dir/main.cpp.o: CMakeFiles/OCR.dir/flags.make
CMakeFiles/OCR.dir/main.cpp.o: main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/elhadji/Bureau/ProjetOCR/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/OCR.dir/main.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/OCR.dir/main.cpp.o -c /home/elhadji/Bureau/ProjetOCR/src/main.cpp

CMakeFiles/OCR.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/OCR.dir/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/elhadji/Bureau/ProjetOCR/src/main.cpp > CMakeFiles/OCR.dir/main.cpp.i

CMakeFiles/OCR.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/OCR.dir/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/elhadji/Bureau/ProjetOCR/src/main.cpp -o CMakeFiles/OCR.dir/main.cpp.s

CMakeFiles/OCR.dir/NN2.cpp.o: CMakeFiles/OCR.dir/flags.make
CMakeFiles/OCR.dir/NN2.cpp.o: NN2.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/elhadji/Bureau/ProjetOCR/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/OCR.dir/NN2.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/OCR.dir/NN2.cpp.o -c /home/elhadji/Bureau/ProjetOCR/src/NN2.cpp

CMakeFiles/OCR.dir/NN2.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/OCR.dir/NN2.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/elhadji/Bureau/ProjetOCR/src/NN2.cpp > CMakeFiles/OCR.dir/NN2.cpp.i

CMakeFiles/OCR.dir/NN2.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/OCR.dir/NN2.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/elhadji/Bureau/ProjetOCR/src/NN2.cpp -o CMakeFiles/OCR.dir/NN2.cpp.s

CMakeFiles/OCR.dir/Timer.cpp.o: CMakeFiles/OCR.dir/flags.make
CMakeFiles/OCR.dir/Timer.cpp.o: Timer.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/elhadji/Bureau/ProjetOCR/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/OCR.dir/Timer.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/OCR.dir/Timer.cpp.o -c /home/elhadji/Bureau/ProjetOCR/src/Timer.cpp

CMakeFiles/OCR.dir/Timer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/OCR.dir/Timer.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/elhadji/Bureau/ProjetOCR/src/Timer.cpp > CMakeFiles/OCR.dir/Timer.cpp.i

CMakeFiles/OCR.dir/Timer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/OCR.dir/Timer.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/elhadji/Bureau/ProjetOCR/src/Timer.cpp -o CMakeFiles/OCR.dir/Timer.cpp.s

CMakeFiles/OCR.dir/tests/test_xor.cpp.o: CMakeFiles/OCR.dir/flags.make
CMakeFiles/OCR.dir/tests/test_xor.cpp.o: tests/test_xor.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/elhadji/Bureau/ProjetOCR/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/OCR.dir/tests/test_xor.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/OCR.dir/tests/test_xor.cpp.o -c /home/elhadji/Bureau/ProjetOCR/src/tests/test_xor.cpp

CMakeFiles/OCR.dir/tests/test_xor.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/OCR.dir/tests/test_xor.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/elhadji/Bureau/ProjetOCR/src/tests/test_xor.cpp > CMakeFiles/OCR.dir/tests/test_xor.cpp.i

CMakeFiles/OCR.dir/tests/test_xor.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/OCR.dir/tests/test_xor.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/elhadji/Bureau/ProjetOCR/src/tests/test_xor.cpp -o CMakeFiles/OCR.dir/tests/test_xor.cpp.s

# Object files for target OCR
OCR_OBJECTS = \
"CMakeFiles/OCR.dir/main.cpp.o" \
"CMakeFiles/OCR.dir/NN2.cpp.o" \
"CMakeFiles/OCR.dir/Timer.cpp.o" \
"CMakeFiles/OCR.dir/tests/test_xor.cpp.o"

# External object files for target OCR
OCR_EXTERNAL_OBJECTS =

OCR: CMakeFiles/OCR.dir/main.cpp.o
OCR: CMakeFiles/OCR.dir/NN2.cpp.o
OCR: CMakeFiles/OCR.dir/Timer.cpp.o
OCR: CMakeFiles/OCR.dir/tests/test_xor.cpp.o
OCR: CMakeFiles/OCR.dir/build.make
OCR: /usr/lib/x86_64-linux-gnu/libpython3.8.so
OCR: CMakeFiles/OCR.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/elhadji/Bureau/ProjetOCR/src/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Linking CXX executable OCR"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/OCR.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/OCR.dir/build: OCR

.PHONY : CMakeFiles/OCR.dir/build

CMakeFiles/OCR.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/OCR.dir/cmake_clean.cmake
.PHONY : CMakeFiles/OCR.dir/clean

CMakeFiles/OCR.dir/depend:
	cd /home/elhadji/Bureau/ProjetOCR/src && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/elhadji/Bureau/ProjetOCR /home/elhadji/Bureau/ProjetOCR /home/elhadji/Bureau/ProjetOCR/src /home/elhadji/Bureau/ProjetOCR/src /home/elhadji/Bureau/ProjetOCR/src/CMakeFiles/OCR.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/OCR.dir/depend

