# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

CMakeFiles/OCR.dir/NN2.cpp.o: ../include/NN2.h
CMakeFiles/OCR.dir/NN2.cpp.o: NN2.cpp

CMakeFiles/OCR.dir/Timer.cpp.o: Timer.cpp
CMakeFiles/OCR.dir/Timer.cpp.o: Timer.h

CMakeFiles/OCR.dir/main.cpp.o: ../include/NN2.h
CMakeFiles/OCR.dir/main.cpp.o: ../include/test_xor.h
CMakeFiles/OCR.dir/main.cpp.o: Timer.h
CMakeFiles/OCR.dir/main.cpp.o: main.cpp

CMakeFiles/OCR.dir/tests/test_xor.cpp.o: ../include/NN2.h
CMakeFiles/OCR.dir/tests/test_xor.cpp.o: ../include/test_xor.h
CMakeFiles/OCR.dir/tests/test_xor.cpp.o: tests/test_xor.cpp

